### PR TITLE
Minor edits

### PR DESCRIPTION
**Pull request by freiburgermsu**
Hello @Fxe ,

Here are minor edits. 

- Existing periodic table and MW modules are leveraged. 
- A few instances of `|=` are replaced with `.update()`, which supports older Python versions while performing the same function of concatenating sets.
- An unused argument is flagged.
- Ambiguous variables are clarified.
- An exception file is created to store custom exception classes that are used in various packages.

Andrew

### CODE REVIEW

**Comment by freiburgermsu** [comment]
The `setup.py`, `README`, and `test_data` should have been added to the last PR but were somehow missed in my PR. 

- The `setup.py` adds imports that are necessary for the new content and adds URLs that will automatically render in the PyPI index. 
- The `test_data` includes local import of the the ecoli core model -- since `cobra.tests` throws a `ModuleNotFoundError` -- and is bundled with the other ModelSEEDpy content for use with the package in Notebooks or other packages as an example model.

The PR is passing.

Andrew

**Comment by Fxe** [comment]
- **test data does not go into main**
- readme should not point to your url
- why we need cython as requirement?

**Comment by freiburgermsu** [comment]
Hello @Fxe ,

- `test_data` was relocated to `tests`
- The README paths are corrected to the main repository
- `cython` is used in a number of my forthcoming packages.

**Comment by Fxe** [comment]
> * `cython` is used in a number of my forthcoming packages.

That does not explain why you need it

**Comment by freiburgermsu** [comment]
Cython is used to compile Python scripts into C, which can be imported into a Python file and read by the Python interpreter: e.g. `PkgWithCython.c` is a compile Python package that can be imported normally via `import PkgWithCython` but it has C speeds. Here is the [original publication](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=5582062).

A few of my community and constraint packages are very computational extensive, and thus use Cython to optimize performance without deviating from standard Python compatibility.

**Comment by Fxe** [comment]
I known what cython is for and it is a problem (same issue that pyeda brings)
leave it out for now, and if actually required then we have move it to another repo like modelseedpy-community

**Comment by freiburgermsu** [comment]
What is the problem? Why can cython compiled packages for the various operating systems not be created and stored in the same directory, where the interpreter would find the appropriate format for the user's operating system?

**Comment by Fxe** [comment]
that is something to be tested unless you already have a working demo

**Comment by freiburgermsu** [comment]
I justed commented the cython requirement for the PR, since none of the current packages in MSpy require it.

I will share a demo of cython with various operating systems during this evening.

**Comment by freiburgermsu** [comment]
I discovered that cython does not substantially expedite Optlang operations, so I may not use cython. All references to cython are removed. The PR is passing.

Andrew

**Pull request merged**
