### PR TITLE
docs, examples, and tests updates

### PR DESCRIPTION
**Pull request by freiburgermsu**
Hello @Fxe ,

Here is a PR with only changes to the docs, examples, and tests, per your suggestion. I will parse other changes as organized PRs later today.

Thank you :)
    Andrew

### CODE REVIEW

**Comment by freiburgermsu** [comment]
Hello @Fxe ,

This PR is passing. The only changed files that may interest you:

1. MSeditor 

- heeded Chris' comment to remove unused imports
- ``remove_reaction`` now optionally accepts MS reaction IDs, whereas before it throws an error and only accepts BiGG reaction IDs

3. MSgenome 

- An error with the unit-test was corrected by uncommenting a line
- clarified the ``ontology`` variable
- list comprehension

**Comment by Fxe** [comment]
@freiburgermsu why are you pulling prs 1 by 1 I get a ton o email spam because of this ...

**Comment by Fxe** [comment]
@freiburgermsu also test data/mock does not go into main (modelseedpy) they stay in test

**Comment by freiburgermsu** [comment]
I only submitted one PR. I did not realize that subsequent commits trigger email alerts.

I relocated test_data to test. 

Thank you,
    Andrew

**Pull request merged**
